---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gber-cert
  namespace: default
spec:
  secretName: gber-cert
  issuerRef:
    name: letsencrypt
  commonName: foohogebar.tk
  dnsNames:
  - foohogebar.tk
  acme:
    config:
    - http01:
        ingress: gber-ingress
      domains:
      - foohogebar.tk